# =====================================================================================
# Configuration for the RL environment and training setup.
# Every parameters except quadrotor configuration is included here.

# For more details, please refer to the documentation.
# https://isaac-sim.github.io/IsaacLab/main/source/api/lab/isaaclab.app.html#isaaclab.app.AppLauncher
# https://isaac-sim.github.io/IsaacLab/main/source/api/lab/isaaclab.scene.html#isaaclab.scene.InteractiveSceneCfg
# https://isaac-sim.github.io/IsaacLab/main/source/api/lab/isaaclab.envs.html#isaaclab.envs.ManagerBasedRLEnvCfg
# =====================================================================================




# ─────────────────────────────────────────────────────────────────────────────────────
# Configuration of Isaac Lab Launcher
# This section includes basic settings for Isaac Lab and the simulation.
# ─────────────────────────────────────────────────────────────────────────────────────

LAUNCHER:
  HEADLESS: false            # Whether to run in headless mode
  DEVICE: "cuda:0"           # Device to run the simulation on
  USE_MANUAL_ACTION: false   # Only for testing. If true, use the action specified below.
  MANUAL_ACTION: [0,0,0,0]

# ─────────────────────────────────────────────────────────────────────────────────────
# Configuration of the Scene and Environment
# This section includes settings for the scene and the RL environment.
# ─────────────────────────────────────────────────────────────────────────────────────

SCENE:
  NUM_ENVS: 256              # Number of parallel environments
  ENV_SPACING: 0.5          # Spacing between environments (m)
  CLONE_IN_FABRIC: true     # If true, entities are cloned in fabric for better performance
  FILTER_COLLISIONS: true   # If true, collisions will not occur between cloned entities

ENV:
  PHYSICS_DT: 0.005          # Physics timestep (200 Hz)
  DECIMATION: 2             # Number of physics steps per control step (2 * 0.005 = 0.01s, 100 Hz)
  EPISODE_LENGTH_S: 25.0    # Length of each episode in seconds
  VIEWER: [3.0, 3.0, 2.0]   # Initial camera position in the viewer


# ─────────────────────────────────────────────────────────────────────────────────────
# Configuration of the Reinforcement Learning
# This section includes settings for the event, observation, reward, and termination.
# ─────────────────────────────────────────────────────────────────────────────────────

EVENT:
  LIN_VEL_MIN: [1.5, 1.5, 1.5]     # Minimum linear velocity (m/s)
  LIN_VEL_MAX: [2.0, 2.0, 2.0]       # Maximum linear velocity (m/s)
  ANG_VEL_MIN: [-2.0, -2.0, -2.0]    # Minimum angular velocity (rad/s)
  ANG_VEL_MAX: [2.0, 2.0, 2.0]       # Maximum angular velocity (rad/s)
  TILT_RANGE_DEG: [30, 40]           # Maximum tilt angle (degrees)
  YAW_DEGREE_RANGE: [-45.0, 45.0]  # Range of yaw angle (degrees)
  OMEGA_NORM_MAX: 10.0                # Maximum angular velocity norm (rad/s)
  
OBSERVATION:
  CONCATENATE_TERMS: true   # If true, concatenate observation terms into a single vector
  ENABLE_CORRUPTION: false  # If true, add noise to observations

REWARD:
  POS_ERR_HALF: 1.3         # Position error reward drops to half (m)
  LIN_VEL_HALF: 0.7         # Linear velocity reward drops to half (m/s)
  ANG_VEL_HALF: 1.5         # Angular velocity reward drops to half (rad/s)
  ORI_ERR_HALF: 0.15         # Orientation error reward drops to half (rad)
  POS_ERR_WEIGHT: 1.2       # Weight for position error reward
  LIN_VEL_WEIGHT: 0.25       # Weight for linear velocity reward
  ANG_VEL_WEIGHT: 0.04       # Weight for angular velocity reward
  ORI_ERR_WEIGHT: 0.05       # Weight for orientation error reward
  TIME_PENALTY_WEIGHT: 5.0   # Weight for time penalty
  STABILIZED_BONUS_WEIGHT: 1500.0 # Weight for stabilized bonus
  ABNORMAL_PENALTY_WEIGHT: 700.0  # Weight for abnormal penalty

STABILIZATION:
  POS_ERR_TOL: 0.8          # Position error threshold for determine stabilization (m)
  LIN_VEL_TOL: 0.3          # Linear velocity threshold for determine stabilization (m/s)
  ANG_VEL_TOL: 0.3          # Angular velocity threshold for determine stabilization (rad/s)
  TILT_DEGREE_TOL: 5.0     # Tilt angle threshold for determine stabilization (degrees)

TERMINATION:
  FLIP_TILT_DEGREE: 90.0    # Terminate if tilt angle exceeds (degrees)
  DIST_THRESHOLD: 20.0      # Terminate if distance from spawn exceeds (m)
  ALTITUDE_THRESHOLD: 0.02  # Terminate if altitude is below (m)

CASCADE_CONTROLLER: 
  POS_P: [1.21, 1.21, 1.21] # Proportional gain for position controller
  POS_SLEW_MAX: 10.0     # Maximum slew rate for position controller (m)
  VEL_P: [2.3, 2.3, 2.3] # Proportional gain for velocity controller 
  VEL_I: [0.02, 0.02, 0.2] # Integral gain for velocity controller 
  ATT_P: [3.85, 3.85, 1.5] # Proportional gain for attitude controller 
  TILT_MAX: [25.0] # Maximum tilt angle (degrees) 
  RATE_P: [10.3, 10.3, 3.0] # Proportional gain for angular rate controller 
  RATE_I: [0.01, 0.01, 0.02] # Integral gain for angular rate controller 
  VEL_LIMIT: [2.6, 2.6, 0.65] # Velocity limit (m/s) 
  ANG_VEL_LIMIT: [4.5, 4.5, 1.0] # Angular velocity limit (rad/s) 
  ACC_LIMIT: [8.0, 8.0, 8.0] # Acceleration limit (m/s^2) 
  TORQUE_LIMIT: [0.01, 0.01, 0.001] # Torque limit (N*m) 
  VEL_I_CLAMP: [0.4, 0.4, 0.2] # Integral windup limit for velocity controller 
  RATE_I_CLAMP: [0.15, 0.15, 0.1] # Integral windup limit for angular rate controller


